---
- name: Provisioning AWS instance Using Ansible
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - vars/aws-cred.yml
  
  tasks:
  
  - name: Use Ansible amazon.aws.ec2 module to launch an aws instance
    amazon.aws.ec2:
      key_name: "{{ ec2_keypair }}"
      group_id: "{{ ec2_security_group }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
      region: "{{ ec2_region }}"
      instance_tags: 
        Name: "{{ec2_tag_Name}}"
      assign_public_ip: yes
      wait: true
      count: 1
      volumes: 
        - device_name: /dev/sda1
          device_type: gp2
          volume_size: "{{ ec2_volume_size }}"
          delete_on_termination: true
    register: ec2

  - debug: var=ec2.instances
    
